"""Trigram-based language plausibility scoring for layout-mismatch detection.

Decides whether a string reads as Russian or English by what fraction of its
character trigrams appear in a frequency-ranked set of that language's common
trigrams. The tables are embedded `.py` constants (no corpus file, no
package-data); they are regenerated from hunspell wordlists by
`scripts/gen_trigrams.py` (top 900 boundary-padded trigrams per language). The
layout fixer only compares two candidate spellings and picks the more plausible
one, so relative coverage is what matters.

Trigrams are counted over the word *padded with spaces* (`" word "`), so the
first/last trigram of every word — and short function words — get represented;
`_trigrams` pads identically at score time. `score("привет") -> {"ru": ...,
"en": 0.0}`. Callers compare the score of two candidate spellings (the text as
typed vs. its layout re-key) to pick a winner.
"""

from __future__ import annotations

# Top 900 space-padded Russian trigrams by vocabulary frequency (hunspell ru_RU).
_RU_TRIGRAMS: frozenset[str] = frozenset(
    [
        " ав",
        " ак",
        " ал",
        " ан",
        " ар",
        " ба",
        " бе",
        " бл",
        " бо",
        " бр",
        " бу",
        " ва",
        " ве",
        " вз",
        " ви",
        " во",
        " вс",
        " вы",
        " га",
        " ге",
        " ги",
        " гл",
        " го",
        " гр",
        " дв",
        " де",
        " ди",
        " до",
        " др",
        " за",
        " из",
        " ин",
        " ис",
        " ка",
        " ки",
        " кл",
        " ко",
        " кр",
        " ку",
        " ла",
        " ле",
        " ли",
        " ло",
        " ма",
        " ме",
        " ми",
        " мо",
        " му",
        " на",
        " не",
        " ни",
        " но",
        " об",
        " од",
        " ок",
        " оп",
        " ос",
        " от",
        " па",
        " пе",
        " пи",
        " пл",
        " по",
        " пр",
        " пу",
        " ра",
        " ре",
        " ро",
        " ру",
        " са",
        " св",
        " се",
        " си",
        " ск",
        " сл",
        " см",
        " со",
        " сп",
        " ст",
        " су",
        " та",
        " те",
        " то",
        " тр",
        " ту",
        " уд",
        " уп",
        " ус",
        " ут",
        " фа",
        " фи",
        " фо",
        " че",
        " эк",
        "аба",
        "або",
        "ава",
        "аве",
        "ави",
        "авл",
        "авн",
        "аво",
        "авш",
        "аго",
        "агр",
        "ада",
        "аде",
        "ади",
        "адо",
        "аем",
        "ажи",
        "аза",
        "азв",
        "азд",
        "ази",
        "азм",
        "азн",
        "азо",
        "аив",
        "ака",
        "ако",
        "акт",
        "ала",
        "але",
        "али",
        "алл",
        "ало",
        "аль",
        "ама",
        "аме",
        "ами",
        "амо",
        "ан ",
        "ана",
        "анд",
        "ане",
        "ани",
        "анк",
        "анн",
        "ано",
        "анс",
        "ант",
        "анц",
        "апа",
        "апо",
        "апр",
        "ара",
        "аре",
        "ари",
        "арк",
        "арн",
        "аро",
        "арт",
        "аск",
        "асп",
        "асс",
        "аст",
        "ат ",
        "ата",
        "ате",
        "ати",
        "ато",
        "атр",
        "аты",
        "ать",
        "афи",
        "аци",
        "ачи",
        "аши",
        "ащи",
        "ающ",
        "бал",
        "без",
        "бел",
        "бер",
        "бес",
        "бив",
        "бит",
        "бла",
        "бле",
        "бли",
        "бол",
        "бор",
        "бра",
        "бре",
        "бри",
        "бро",
        "вав",
        "вае",
        "вал",
        "ван",
        "вар",
        "ват",
        "ваю",
        "вед",
        "вен",
        "вер",
        "вес",
        "вет",
        "вив",
        "вид",
        "вин",
        "вис",
        "вит",
        "вич",
        "вка",
        "вле",
        "вля",
        "вно",
        "вны",
        "во ",
        "вов",
        "вод",
        "воз",
        "вой",
        "вол",
        "вор",
        "вос",
        "вск",
        "вто",
        "вши",
        "выв",
        "вый",
        "вык",
        "вып",
        "выр",
        "выс",
        "гав",
        "ган",
        "гат",
        "ген",
        "гив",
        "гия",
        "гла",
        "гну",
        "гов",
        "гол",
        "гон",
        "гор",
        "гра",
        "гре",
        "гру",
        "гры",
        "дав",
        "дат",
        "дви",
        "дев",
        "дел",
        "ден",
        "дер",
        "дет",
        "див",
        "дин",
        "дио",
        "дир",
        "дит",
        "дни",
        "дно",
        "дны",
        "доб",
        "дов",
        "док",
        "дол",
        "доп",
        "дор",
        "дос",
        "дра",
        "дре",
        "дро",
        "дст",
        "дыв",
        "ев ",
        "ева",
        "еве",
        "еви",
        "ево",
        "евш",
        "евы",
        "еда",
        "еде",
        "еди",
        "едо",
        "еза",
        "ей ",
        "ейш",
        "ек ",
        "ека",
        "еко",
        "ект",
        "еле",
        "ели",
        "ело",
        "ель",
        "ем ",
        "еме",
        "емо",
        "емы",
        "ен ",
        "ена",
        "ене",
        "ени",
        "енн",
        "ено",
        "ент",
        "ень",
        "епл",
        "епо",
        "епр",
        "ер ",
        "ера",
        "ерг",
        "ере",
        "ерж",
        "ери",
        "ерк",
        "ерм",
        "ерн",
        "еро",
        "ерс",
        "ерт",
        "еск",
        "есс",
        "ест",
        "ет ",
        "ета",
        "ете",
        "ети",
        "етн",
        "ето",
        "етр",
        "етс",
        "еть",
        "ец ",
        "ече",
        "ешь",
        "жат",
        "жда",
        "жен",
        "жив",
        "жит",
        "заб",
        "зав",
        "заг",
        "зад",
        "зак",
        "зам",
        "зан",
        "зап",
        "зар",
        "зас",
        "зат",
        "зац",
        "зве",
        "зво",
        "зир",
        "зм ",
        "зна",
        "зны",
        "зов",
        "зыв",
        "ива",
        "иви",
        "ивн",
        "иво",
        "ивш",
        "ига",
        "иде",
        "ие ",
        "иза",
        "изв",
        "изи",
        "изм",
        "изо",
        "ий ",
        "ийс",
        "ик ",
        "ика",
        "ико",
        "или",
        "ило",
        "иль",
        "има",
        "име",
        "ими",
        "имо",
        "ин ",
        "ина",
        "ине",
        "ини",
        "ино",
        "инс",
        "инт",
        "ион",
        "ира",
        "иро",
        "иру",
        "иск",
        "исл",
        "исп",
        "ист",
        "ит ",
        "ита",
        "ите",
        "ити",
        "ито",
        "ить",
        "ица",
        "ици",
        "ича",
        "иче",
        "ичн",
        "ия ",
        "йся",
        "йши",
        "ка ",
        "кав",
        "каз",
        "кал",
        "кан",
        "кар",
        "кат",
        "кив",
        "кий",
        "кин",
        "кла",
        "кле",
        "кну",
        "ков",
        "кол",
        "ком",
        "кон",
        "коп",
        "кор",
        "кос",
        "кра",
        "кре",
        "кри",
        "кро",
        "кру",
        "кти",
        "кто",
        "ктр",
        "кул",
        "куп",
        "кур",
        "ла ",
        "лав",
        "лаг",
        "лад",
        "лам",
        "лан",
        "лас",
        "лат",
        "лев",
        "лек",
        "лен",
        "леп",
        "лес",
        "лет",
        "лив",
        "лиз",
        "лик",
        "лин",
        "лир",
        "лис",
        "лит",
        "лич",
        "лка",
        "лли",
        "лов",
        "лог",
        "лод",
        "лок",
        "лом",
        "лон",
        "лос",
        "лот",
        "лоч",
        "лый",
        "ль ",
        "льн",
        "льс",
        "льт",
        "ляв",
        "лят",
        "ляю",
        "лён",
        "ма ",
        "мал",
        "ман",
        "мар",
        "мат",
        "мел",
        "мен",
        "мер",
        "мет",
        "мин",
        "мир",
        "мит",
        "мно",
        "мол",
        "мон",
        "мор",
        "мос",
        "мот",
        "мый",
        "на ",
        "нав",
        "над",
        "нак",
        "нал",
        "нам",
        "нап",
        "нар",
        "нас",
        "нат",
        "нев",
        "нед",
        "ней",
        "нен",
        "неп",
        "нер",
        "нес",
        "нет",
        "нец",
        "нив",
        "ние",
        "низ",
        "ник",
        "ним",
        "нир",
        "нис",
        "нит",
        "ниц",
        "нич",
        "нка",
        "нни",
        "нно",
        "нны",
        "нов",
        "ног",
        "ной",
        "нок",
        "нос",
        "нск",
        "нст",
        "нта",
        "нте",
        "нти",
        "нто",
        "нтр",
        "нув",
        "нут",
        "нце",
        "ный",
        "ньк",
        "няв",
        "нят",
        "обе",
        "оби",
        "обл",
        "обн",
        "обо",
        "обр",
        "ов ",
        "ова",
        "ове",
        "ови",
        "овк",
        "овн",
        "ово",
        "овы",
        "оги",
        "ого",
        "огр",
        "ода",
        "оде",
        "оди",
        "одн",
        "одо",
        "одр",
        "одс",
        "оду",
        "оже",
        "ожи",
        "оза",
        "озн",
        "ой ",
        "ок ",
        "ока",
        "око",
        "окр",
        "ола",
        "оле",
        "оли",
        "олн",
        "оло",
        "олу",
        "оль",
        "ом ",
        "ома",
        "оме",
        "оми",
        "омо",
        "он ",
        "она",
        "оне",
        "они",
        "онн",
        "оно",
        "онс",
        "онт",
        "ооб",
        "опа",
        "опе",
        "опи",
        "опл",
        "опо",
        "опр",
        "ор ",
        "ора",
        "оре",
        "ори",
        "орм",
        "орн",
        "оро",
        "орт",
        "осв",
        "осе",
        "оси",
        "оск",
        "осл",
        "осн",
        "осо",
        "осп",
        "ост",
        "ота",
        "отв",
        "оте",
        "оти",
        "отк",
        "отн",
        "ото",
        "отр",
        "отс",
        "оче",
        "очи",
        "очк",
        "очн",
        "пал",
        "пан",
        "пар",
        "пас",
        "пат",
        "пер",
        "пир",
        "пис",
        "пит",
        "пла",
        "пле",
        "пло",
        "пов",
        "под",
        "поз",
        "пок",
        "пол",
        "пом",
        "пон",
        "поп",
        "пор",
        "пос",
        "пот",
        "пра",
        "пре",
        "при",
        "про",
        "пря",
        "пус",
        "ра ",
        "раб",
        "рав",
        "рад",
        "раж",
        "раз",
        "рак",
        "рал",
        "рам",
        "ран",
        "рас",
        "рат",
        "раф",
        "реб",
        "рев",
        "рег",
        "ред",
        "реж",
        "рез",
        "рек",
        "рел",
        "рем",
        "рен",
        "реп",
        "рес",
        "рет",
        "рех",
        "рив",
        "риг",
        "риз",
        "рик",
        "рим",
        "рин",
        "рип",
        "рир",
        "рис",
        "рит",
        "рич",
        "рка",
        "рма",
        "рно",
        "рны",
        "роб",
        "ров",
        "рог",
        "род",
        "рож",
        "роз",
        "рои",
        "рок",
        "рол",
        "ром",
        "рон",
        "роп",
        "рос",
        "рот",
        "роч",
        "рош",
        "рск",
        "рст",
        "рти",
        "руб",
        "руе",
        "руж",
        "рую",
        "рыв",
        "рыз",
        "сам",
        "сан",
        "све",
        "сел",
        "сер",
        "син",
        "сир",
        "сит",
        "ска",
        "ски",
        "ско",
        "скр",
        "ску",
        "сла",
        "сле",
        "сло",
        "сме",
        "сны",
        "сов",
        "сол",
        "сор",
        "сос",
        "спа",
        "спе",
        "спи",
        "спл",
        "спо",
        "спр",
        "сси",
        "ст ",
        "ста",
        "ств",
        "сте",
        "сти",
        "стн",
        "сто",
        "стр",
        "сту",
        "сты",
        "сть",
        "сыв",
        "сь ",
        "ся ",
        "та ",
        "тав",
        "тал",
        "тан",
        "тар",
        "тат",
        "тве",
        "тво",
        "те ",
        "тек",
        "тел",
        "тен",
        "тер",
        "тес",
        "тив",
        "тик",
        "тил",
        "тин",
        "тир",
        "тис",
        "тит",
        "тич",
        "тка",
        "тни",
        "тно",
        "тны",
        "тов",
        "тол",
        "том",
        "тон",
        "топ",
        "тор",
        "тос",
        "точ",
        "тра",
        "тре",
        "три",
        "тро",
        "тру",
        "тск",
        "тст",
        "тся",
        "тур",
        "тыв",
        "тый",
        "ть ",
        "тьс",
        "увш",
        "удо",
        "уем",
        "ует",
        "ули",
        "уль",
        "ура",
        "ури",
        "уст",
        "ут ",
        "уты",
        "уть",
        "уча",
        "учи",
        "уши",
        "уют",
        "ующ",
        "фор",
        "хва",
        "ход",
        "ца ",
        "цев",
        "цем",
        "цен",
        "цио",
        "цир",
        "ция",
        "чав",
        "чат",
        "чен",
        "чер",
        "чес",
        "чет",
        "чив",
        "чик",
        "чит",
        "чка",
        "чно",
        "чны",
        "шен",
        "шив",
        "ший",
        "шка",
        "шь ",
        "щен",
        "щий",
        "щик",
        "ыва",
        "ый ",
        "ье ",
        "ьни",
        "ьно",
        "ьны",
        "ься",
        "эле",
        "ютс",
        "ющи",
        "явш",
        "яем",
        "яти",
        "ять",
        "ящи",
        "яющ",
        "ённ",
        "ёт ",
    ]
)

# Top 900 space-padded English trigrams by vocabulary frequency (hunspell en_US).
_EN_TRIGRAMS: frozenset[str] = frozenset(
    [
        " ab",
        " ac",
        " ad",
        " al",
        " am",
        " an",
        " ap",
        " ar",
        " as",
        " at",
        " au",
        " ba",
        " be",
        " bi",
        " bl",
        " bo",
        " br",
        " bu",
        " ca",
        " ce",
        " ch",
        " ci",
        " cl",
        " co",
        " cr",
        " cu",
        " da",
        " de",
        " di",
        " do",
        " dr",
        " du",
        " el",
        " em",
        " en",
        " ex",
        " fa",
        " fe",
        " fi",
        " fl",
        " fo",
        " fr",
        " fu",
        " ga",
        " ge",
        " gi",
        " gl",
        " go",
        " gr",
        " gu",
        " ha",
        " he",
        " hi",
        " ho",
        " hu",
        " hy",
        " im",
        " in",
        " ir",
        " ja",
        " je",
        " jo",
        " ju",
        " ka",
        " ki",
        " la",
        " le",
        " li",
        " lo",
        " lu",
        " ma",
        " me",
        " mi",
        " mo",
        " mu",
        " na",
        " ne",
        " ni",
        " no",
        " ob",
        " or",
        " ou",
        " ov",
        " pa",
        " pe",
        " ph",
        " pi",
        " pl",
        " po",
        " pr",
        " pu",
        " qu",
        " ra",
        " re",
        " ri",
        " ro",
        " ru",
        " sa",
        " sc",
        " se",
        " sh",
        " si",
        " sl",
        " sn",
        " so",
        " sp",
        " st",
        " su",
        " sw",
        " sy",
        " ta",
        " te",
        " th",
        " ti",
        " to",
        " tr",
        " tu",
        " un",
        " va",
        " ve",
        " vi",
        " wa",
        " we",
        " wh",
        " wi",
        " wo",
        "abb",
        "abi",
        "abl",
        "acc",
        "ace",
        "ach",
        "aci",
        "ack",
        "act",
        "ad ",
        "ade",
        "adi",
        "age",
        "agg",
        "ail",
        "ain",
        "air",
        "ake",
        "al ",
        "ala",
        "ale",
        "ali",
        "all",
        "alo",
        "alt",
        "am ",
        "ama",
        "amb",
        "ame",
        "ami",
        "amm",
        "amp",
        "an ",
        "ana",
        "anc",
        "and",
        "ane",
        "ang",
        "ani",
        "ank",
        "ann",
        "ano",
        "ans",
        "ant",
        "ape",
        "aph",
        "app",
        "ar ",
        "ara",
        "arc",
        "ard",
        "are",
        "ari",
        "ark",
        "arl",
        "arm",
        "arr",
        "art",
        "ary",
        "ase",
        "ash",
        "asi",
        "ass",
        "ast",
        "at ",
        "ata",
        "ate",
        "ath",
        "ati",
        "ato",
        "atr",
        "att",
        "aut",
        "ave",
        "avi",
        "ay ",
        "bac",
        "bal",
        "ban",
        "bar",
        "bat",
        "bea",
        "bel",
        "ber",
        "bil",
        "bin",
        "bit",
        "bla",
        "ble",
        "blo",
        "bly",
        "boa",
        "boo",
        "bor",
        "bra",
        "bre",
        "bri",
        "bro",
        "bul",
        "bur",
        "cal",
        "can",
        "cap",
        "car",
        "cas",
        "cat",
        "ce ",
        "cel",
        "cen",
        "cer",
        "ch ",
        "cha",
        "che",
        "chi",
        "cho",
        "cia",
        "cin",
        "cit",
        "ck ",
        "cke",
        "cla",
        "cle",
        "clo",
        "col",
        "com",
        "con",
        "cor",
        "cou",
        "cra",
        "cre",
        "cri",
        "cro",
        "cru",
        "ct ",
        "cti",
        "cto",
        "cul",
        "cur",
        "cy ",
        "dal",
        "dan",
        "de ",
        "dec",
        "ded",
        "del",
        "dem",
        "den",
        "der",
        "des",
        "dge",
        "dia",
        "dic",
        "din",
        "dio",
        "dis",
        "dit",
        "dle",
        "dne",
        "dra",
        "dro",
        "duc",
        "dy ",
        "ead",
        "eal",
        "ean",
        "ear",
        "eas",
        "eat",
        "eco",
        "ect",
        "ed ",
        "edi",
        "ee ",
        "eed",
        "een",
        "ega",
        "ein",
        "el ",
        "ela",
        "ele",
        "eli",
        "ell",
        "ema",
        "eme",
        "emi",
        "emo",
        "emp",
        "en ",
        "ena",
        "enc",
        "end",
        "ene",
        "eni",
        "enn",
        "eno",
        "ens",
        "ent",
        "ept",
        "er ",
        "era",
        "erb",
        "erc",
        "ere",
        "erg",
        "eri",
        "erl",
        "erm",
        "ern",
        "ero",
        "erp",
        "err",
        "ers",
        "ert",
        "erv",
        "ery",
        "es ",
        "esc",
        "ese",
        "esi",
        "ess",
        "est",
        "et ",
        "eta",
        "ete",
        "eth",
        "eti",
        "etr",
        "ett",
        "eve",
        "exp",
        "ext",
        "ey ",
        "fer",
        "fic",
        "fin",
        "fla",
        "for",
        "fra",
        "fre",
        "ful",
        "gal",
        "gan",
        "gar",
        "gat",
        "ge ",
        "gen",
        "ger",
        "gge",
        "ggi",
        "ght",
        "gic",
        "gin",
        "gis",
        "gle",
        "gra",
        "gre",
        "gro",
        "gy ",
        "hal",
        "ham",
        "han",
        "har",
        "hea",
        "hel",
        "hen",
        "her",
        "hic",
        "hil",
        "hin",
        "hip",
        "hol",
        "hon",
        "hoo",
        "hor",
        "hou",
        "hro",
        "hs ",
        "ht ",
        "hy ",
        "ia ",
        "ial",
        "ian",
        "iat",
        "ibl",
        "ic ",
        "ica",
        "ice",
        "ici",
        "ick",
        "id ",
        "ide",
        "idi",
        "ie ",
        "ien",
        "ier",
        "ifi",
        "igh",
        "ign",
        "il ",
        "ila",
        "ile",
        "ili",
        "ill",
        "ily",
        "ima",
        "ime",
        "imi",
        "imm",
        "imp",
        "in ",
        "ina",
        "inc",
        "ind",
        "ine",
        "inf",
        "ing",
        "ini",
        "ink",
        "inn",
        "ino",
        "ins",
        "int",
        "ion",
        "iou",
        "ip ",
        "ipp",
        "ire",
        "is ",
        "isc",
        "ise",
        "ish",
        "isi",
        "ism",
        "iss",
        "ist",
        "it ",
        "ita",
        "ite",
        "ith",
        "iti",
        "ito",
        "itt",
        "itu",
        "ity",
        "ium",
        "ive",
        "ivi",
        "iza",
        "ize",
        "ke ",
        "ker",
        "kin",
        "ky ",
        "la ",
        "lac",
        "lam",
        "lan",
        "lar",
        "las",
        "lat",
        "lay",
        "ld ",
        "le ",
        "lea",
        "lec",
        "leg",
        "lem",
        "len",
        "ler",
        "les",
        "let",
        "lia",
        "lic",
        "lie",
        "lig",
        "lim",
        "lin",
        "lis",
        "lit",
        "liz",
        "ll ",
        "lla",
        "lle",
        "lli",
        "llo",
        "lly",
        "lne",
        "loc",
        "log",
        "lon",
        "lor",
        "lot",
        "lou",
        "low",
        "lus",
        "ly ",
        "ma ",
        "mac",
        "mag",
        "mal",
        "man",
        "mar",
        "mas",
        "mat",
        "me ",
        "med",
        "mel",
        "men",
        "mer",
        "met",
        "mic",
        "mil",
        "min",
        "mis",
        "mit",
        "mme",
        "mon",
        "mor",
        "mou",
        "mpe",
        "mpl",
        "mul",
        "na ",
        "nal",
        "nan",
        "nar",
        "nat",
        "nce",
        "nch",
        "nci",
        "nco",
        "ncy",
        "nd ",
        "nda",
        "nde",
        "ndi",
        "ndo",
        "ne ",
        "ned",
        "ner",
        "nes",
        "net",
        "ng ",
        "nge",
        "ngl",
        "nia",
        "nic",
        "nin",
        "nis",
        "nit",
        "nk ",
        "nne",
        "nni",
        "non",
        "nor",
        "ns ",
        "nse",
        "nsi",
        "nst",
        "nt ",
        "nta",
        "nte",
        "nth",
        "nti",
        "nto",
        "ntr",
        "ny ",
        "ock",
        "od ",
        "ode",
        "ogi",
        "ogr",
        "ogy",
        "ola",
        "old",
        "ole",
        "oli",
        "oll",
        "olo",
        "om ",
        "oma",
        "ome",
        "omi",
        "omm",
        "omp",
        "on ",
        "ona",
        "onc",
        "ond",
        "one",
        "ong",
        "oni",
        "ono",
        "ons",
        "ont",
        "ood",
        "ook",
        "oot",
        "op ",
        "ope",
        "oph",
        "opp",
        "or ",
        "ora",
        "ord",
        "ore",
        "ori",
        "ork",
        "orm",
        "orn",
        "oro",
        "orr",
        "ors",
        "ort",
        "ory",
        "ose",
        "osi",
        "oss",
        "ost",
        "ot ",
        "ote",
        "oth",
        "oti",
        "oto",
        "ott",
        "oun",
        "our",
        "ous",
        "out",
        "ove",
        "ow ",
        "owe",
        "own",
        "pal",
        "pan",
        "par",
        "pat",
        "pe ",
        "pec",
        "ped",
        "pen",
        "per",
        "pet",
        "pha",
        "phe",
        "phi",
        "pho",
        "pic",
        "pin",
        "pit",
        "pla",
        "ple",
        "pli",
        "pol",
        "por",
        "pos",
        "ppe",
        "ppi",
        "pre",
        "pri",
        "pro",
        "pti",
        "qua",
        "que",
        "qui",
        "ra ",
        "rab",
        "rac",
        "rad",
        "rag",
        "rai",
        "ral",
        "ram",
        "ran",
        "rap",
        "ras",
        "rat",
        "rch",
        "rd ",
        "rdi",
        "re ",
        "rea",
        "rec",
        "red",
        "ree",
        "ref",
        "reg",
        "rel",
        "rem",
        "ren",
        "rep",
        "rer",
        "res",
        "ret",
        "rge",
        "ria",
        "ric",
        "rid",
        "rie",
        "rig",
        "ril",
        "rim",
        "rin",
        "rio",
        "rip",
        "ris",
        "rit",
        "riz",
        "rk ",
        "rma",
        "rmi",
        "rn ",
        "rna",
        "rne",
        "roc",
        "rog",
        "rol",
        "rom",
        "ron",
        "roo",
        "rop",
        "ros",
        "rot",
        "rou",
        "row",
        "rre",
        "rri",
        "rse",
        "rt ",
        "rte",
        "rth",
        "rti",
        "rus",
        "ry ",
        "sal",
        "san",
        "sca",
        "sce",
        "sch",
        "sco",
        "scr",
        "se ",
        "sel",
        "sem",
        "sen",
        "ser",
        "sh ",
        "sha",
        "she",
        "shi",
        "sho",
        "sid",
        "sin",
        "sio",
        "sis",
        "sit",
        "siv",
        "sm ",
        "sma",
        "sne",
        "sol",
        "som",
        "son",
        "sor",
        "spa",
        "spe",
        "spi",
        "spo",
        "ss ",
        "sse",
        "ssi",
        "st ",
        "sta",
        "ste",
        "sti",
        "sto",
        "str",
        "stu",
        "sub",
        "sup",
        "sur",
        "ta ",
        "tab",
        "tai",
        "tal",
        "tan",
        "tar",
        "tat",
        "tch",
        "te ",
        "ted",
        "tee",
        "tel",
        "ten",
        "ter",
        "tes",
        "th ",
        "tha",
        "the",
        "thi",
        "tho",
        "thr",
        "ths",
        "tia",
        "tic",
        "tif",
        "til",
        "tim",
        "tin",
        "tio",
        "tis",
        "tit",
        "tiv",
        "tle",
        "to ",
        "tom",
        "ton",
        "tor",
        "tra",
        "tre",
        "tri",
        "tro",
        "tru",
        "tte",
        "tti",
        "tur",
        "ty ",
        "ual",
        "uck",
        "uct",
        "ue ",
        "ugh",
        "uit",
        "ul ",
        "ula",
        "ull",
        "ult",
        "um ",
        "umb",
        "unc",
        "und",
        "uni",
        "unt",
        "upe",
        "ura",
        "ure",
        "urg",
        "uri",
        "us ",
        "use",
        "usi",
        "usn",
        "ust",
        "ut ",
        "ute",
        "uth",
        "uti",
        "utt",
        "val",
        "ve ",
        "vel",
        "ven",
        "ver",
        "vin",
        "vis",
        "war",
        "wat",
        "way",
        "win",
        "wom",
        "woo",
        "wor",
        "zat",
        "ze ",
    ]
)


def _trigrams(text: str) -> list[str]:
    """Lowercase, space-padded trigrams over the string.

    Padding (`" text "`) mirrors how the tables were built, so a word's edge
    trigrams count and short words (1-2 chars) still yield trigrams instead of
    scoring 0. The empty string pads to two spaces and yields none.
    """
    s = f" {text.lower()} "
    return [s[i : i + 3] for i in range(len(s) - 2)]


def _coverage(grams: list[str], table: frozenset[str]) -> float:
    if not grams:
        return 0.0
    return sum(1 for g in grams if g in table) / len(grams)


def score(text: str) -> dict[str, float]:
    """Fraction of `text`'s trigrams found in each language's common set."""
    grams = _trigrams(text)
    return {"ru": _coverage(grams, _RU_TRIGRAMS), "en": _coverage(grams, _EN_TRIGRAMS)}
